### PR TITLE
Fix issues number 5 and 6 mainly 

### PR DESCRIPTION
**Pull request by nyedidikeke**
- [Build Component (Footer)](https://github.com/oscghana/oscghana-website/issues/6)
- [Build Header Component (Navigation)](https://github.com/oscghana/oscghana-website/issues/5)
- Add Header Component (hero section)
- Add development dependencies and configurations
- Add Sass module

### CODE REVIEW

**Comment by iamsirmike** [comment]
Kindly make the navigation responsive

**Review by oscghanaadmin — COMMENTED** [review]
Kindly make the navigation bar responsive.

**Comment by nyedidikeke** [comment]
> Kindly make the navigation bar responsive.

Responsive navigation added for smaller devices.

**Comment by nyedidikeke** [comment]
> Kindly make the navigation bar responsive.

Completed a week ago.

**Pull request merged**
